[package]
name = "Aether"
version = "0.0.0"
edition = "2024"
build = "build.rs"

[dependencies]
scene_box = { path = "../scene_box" }
cudarc = { version = "*", features = ["cuda-version-from-build-system"] }
winit = "*"
pixels = "*"
serde = { version = "*", features = ["derive"] }
serde_yaml = { package = "serde_yaml_ng", version = "*" }
glam = "*"
bytemuck = { version = "*", features = ["derive"] }
anyhow = "*"
log = "*"
env_logger = "*"
rand = "*"
image = { version = "*", default-features = false, features = ["png"] }
ctrlc = "*"
mimalloc = { version = "*", features = ["v3"] }

[build-dependencies]
glob = "*"

[lints]
workspace = true
